//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunKeeper8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunKeeper8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exerciser.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-Country Skiing.
        /// </summary>
        public static string CrossCountrySkiing {
            get {
                return ResourceManager.GetString("CrossCountrySkiing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycling.
        /// </summary>
        public static string Cycling {
            get {
                return ResourceManager.GetString("Cycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downhill Skiing.
        /// </summary>
        public static string DownhillSkiing {
            get {
                return ResourceManager.GetString("DownhillSkiing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elliptical.
        /// </summary>
        public static string Elliptical {
            get {
                return ResourceManager.GetString("Elliptical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excercise Type.
        /// </summary>
        public static string ExcerciseType {
            get {
                return ResourceManager.GetString("ExcerciseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiking.
        /// </summary>
        public static string Hiking {
            get {
                return ResourceManager.GetString("Hiking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get started.
        /// </summary>
        public static string HomePage1Title {
            get {
                return ResourceManager.GetString("HomePage1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get setup.
        /// </summary>
        public static string HomePage2Title {
            get {
                return ResourceManager.GetString("HomePage2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we configure your phone..
        /// </summary>
        public static string InitialLoadMessage {
            get {
                return ResourceManager.GetString("InitialLoadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Runkeeper.
        /// </summary>
        public static string LoginToRunkeeper {
            get {
                return ResourceManager.GetString("LoginToRunkeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Biking.
        /// </summary>
        public static string MountainBiking {
            get {
                return ResourceManager.GetString("MountainBiking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace.
        /// </summary>
        public static string Pace {
            get {
                return ResourceManager.GetString("Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair with AGENT Smartwatch.
        /// </summary>
        public static string PairWithAgent {
            get {
                return ResourceManager.GetString("PairWithAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rowing.
        /// </summary>
        public static string Rowing {
            get {
                return ResourceManager.GetString("Rowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skating.
        /// </summary>
        public static string Skating {
            get {
                return ResourceManager.GetString("Skating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowboarding.
        /// </summary>
        public static string Snowboarding {
            get {
                return ResourceManager.GetString("Snowboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimming.
        /// </summary>
        public static string Swimming {
            get {
                return ResourceManager.GetString("Swimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        public static string Walking {
            get {
                return ResourceManager.GetString("Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheelchair.
        /// </summary>
        public static string Wheelchair {
            get {
                return ResourceManager.GetString("Wheelchair", resourceCulture);
            }
        }
    }
}
